// <auto-generated />
using System;
using Combats.Services.Battle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Combats.Services.Battle.Migrations
{
    [DbContext(typeof(BattleDbContext))]
    [Migration("20260105072926_RemoveInobox")]
    partial class RemoveInobox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Combats.Services.Battle.Entities.BattleEntity", b =>
                {
                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerBId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("BattleId");

                    b.HasIndex("MatchId");

                    b.ToTable("battles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
